---
# defaults file for neo4j

neo4j_server_database_location: /var/lib/neo4j/data
neo4j_allow_any_connection: false
neo4j_memory_heap_initial_size: 512M
neo4j_memory_heap_max_size: 512M
neo4j_memory_pagecache_size: 512M # default 10g
neo4j_connector_bolt_listen_address: :7687
neo4j_connector_http_listen_address: :7474
neo4j_connector_https_listen_address: :7473
neo4j_prometheus_metrics_enabled: false
neo4j_prometheus_metrics_endpoint: localhost:2004
neo4j_edition: community
# neo4j_password: 'change_me!'
